djangoLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

notes/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('users', views.UserList, name='users'),
    path('user/<int:pk>', views.UserDetailView.as_view(), name='user-detail'),
    path('notes', views.NoteListView.as_view(), name='notes'),
    path('note/<int:pk>', views.NoteDetailView.as_view(), name='note-detail'),
    path('all-tasks', views.TaskListView.as_view(), name='all-tasks'),
    path('mytasks', views.MyTaskView.as_view(), name='my-tasks'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='task-detail'),
    
    # path('note/<int:pk>/renew/', views.RenewNoteDateTask, name='renew-note-date-task'),
    # re_path(r'^note/(?P<pk>[-\w]+)/renew/$', views.RenewNoteStuff, name='renew-note-stuff'),
    path('note/create/', views.NoteCreate.as_view(), name='note-create'),
    path('<int:pk>/update/', views.NoteUpdate.as_view(), name='note-update'),
    path('note/<int:pk>/delete/', views.NoteDelete.as_view(), name='note-delete'),
    path('add-task', views.TaskCreateView.as_view(), name='add-task'),
    ]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from datetime import date

class Author(models.Model):
    """
    Модель представляющая автора.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])


    def __str__(self):
        return self.user.get_full_name()

class Note(models.Model):
    """
    Модель для представления отчета
    """
    title = models.CharField("Заголовок", max_length=100)
    user = models.ForeignKey('Author', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Пользователь')
    date = models.DateField("Дата", auto_now_add=True)
    textarea = models.TextField("Поле для отчета", max_length=1000)

    class Meta:
        verbose_name = 'Отчет'
        verbose_name_plural = 'Отчеты'
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('note-detail', args=[str(self.id)])

class Task(models.Model):
    """
    Модель представляющая задачу
    """
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Уникальный ID для этой задачи")
    user = models.ForeignKey('Author', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Пользователь')
    title = models.CharField("Заголовок", max_length=100)
    created = models.DateField("Создана", auto_now=True)
    closed = models.BooleanField(default=False)
    textarea = models.TextField("Текст задачи", max_length=1000)
    responsible = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS_CHOICES =(
        ('Закрыт', 'Закрыт'),
        ('Открыт', 'Открыт'),
)
    
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True, default='Открыто', help_text='Статус задачи', verbose_name='Статус')

    @property
    def is_overdue(self):
        if self.created and date.today() > self.created:
            return True
        return False

    class Meta:
        ordering = ["created"]
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        permissions = (("can_mark_returned", "Что-то должно тут быть"),)

    def __str__(self):
        return '{0} {1}'.format (self.id, self.title)

    def get_absolute_url(self):
        return reverse('task-detail', args=[str(self.id)])

notes/forms.py
from django.forms import ModelForm
from .models import Task

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime


# class RenewTaskForm(ModelForm): 
#     def clean_closed(self):
#         data = self.cleaned_data['closed']

#        #Проверка того, что дата не в прошлом
#         if data < datetime.date.today():
#            raise ValidationError(_('Invalid date - renewal in past'))

#        #Check date is in range librarian allowed to change (+4 weeks)
#         if data > datetime.date.today() + datetime.timedelta(weeks=4):
#            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

#        # Не забывайте всегда возвращать очищенные данные
#         return data

#     class Meta:
#         model = Task
#         fields = ['closed',]
#         labels = { 'closed': _('Renewal date'), }
#         help_texts = { 'closed': _('Укажите дату от сейчас и до 4 недель вперед.'), }

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
import datetime

# from .forms import RenewTaskForm
from .models import Note, Task, Author


# class UserListView(generic.ListView):
#     model = Author
#     template_name = 'notes/users.html'
#     #context_object_name = 'authors_list'

def UserList(request):
    users_list = Author.objects.all()

    context = {
            "title": "Список пользователей",
            "users_list": users_list,
        }
    return render(request, 'notes/users.html', context)

class UserDetailView(generic.DetailView):
    model = User
    template_name = 'notes/user_detail.html'

class NoteDetailView(generic.DetailView):
    model = Note

class TaskDetailView(generic.DetailView):
    model = Task

class NoteListView(generic.ListView):
    model = Note
    template_name = 'notes/note_list.html'
    paginate_by = 10


class MyTaskView(LoginRequiredMixin,generic.ListView):
    model = Task
    template_name ='notes/my_task.html'
    paginate_by = 2

    def get_queryset(self):
        # return Task.objects.filter(responsible=self.request.user).filter(status__exact='Открыт').order_by('created')
        return Task.objects.filter(user=Author.objects.get(user=self.request.user)).order_by('created').filter(closed=False)


def index(request):
    return render(
        request,
        'notes/index.html',
        context = {
            'title': 'Главная страница',
            }
    )


class TaskListView(PermissionRequiredMixin, generic.ListView):
    model = Task
    permission_required = 'notes.can_mark_returned'
    template_name = 'notes/all_tasks.html'
    paginate_by = 10
    def get_queryset(self):
        return Task.objects.all()

# @permission_required('notes.can_mark_returned')
# def RenewNoteDateTask(request, pk):
#     note_task = get_object_or_404(Task, pk=pk)

#     # Если данный запрос типа POST, тогда
#     if request.method == 'POST':

#         # Создаём экземпляр формы и заполняем данными из запроса (связывание, binding):
#         form = RenewTaskForm(request.POST)

#         # Проверка валидности данных формы:
#         if form.is_valid():
#             # Обработка данных из form.cleaned_data
#             #(здесь мы просто присваиваем их полю closed)
#             note_task.closed = form.cleaned_data['closed']
#             note_task.save()

#             return HttpResponseRedirect(reverse('all-tasks') )

#     # Если это GET (или какой-либо ещё), создать форму по умолчанию.
#     else:
#         proposed_closed = datetime.date.today() + datetime.timedelta(weeks=3)
#         form = RenewTaskForm(initial={'closed': proposed_closed,})

#     return render(
#         request, 
#         'notes/renew_note_date_task.html', 
#         context = {
#             'form': form,
#             'notetask':note_task
#             }
#         )

class NoteCreate(LoginRequiredMixin, CreateView):
    model = Note
    #fields = '__all__'
    fields = ['title', 'textarea']
    success_url = reverse_lazy('notes')
    raise_exception = True
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super(NoteCreate, self).form_valid(form)
    def form_valid(self, form):
        # создаем форму, но не отправляем ее в БД, пока просто держим в памяти
        fields = form.save(commit=False)
        # Через реквест передаем недостающую форму, которая обязательна
        fields.user = Author.objects.get(user=self.request.user)
        # Наконец сохраняем в БД
        fields.save()
        return super().form_valid(form)

class NoteUpdate(LoginRequiredMixin, UpdateView):
    model = Note
    fields = ['title', 'textarea']
    success_url = reverse_lazy('notes')

class NoteDelete(PermissionRequiredMixin, DeleteView):
    model = Note
    permission_required = 'notes.can_mark_returned'
    success_url = reverse_lazy('notes')

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('index')

class TaskCreateView(CreateView):
    model = Task
    template_name = 'notes/add_task.html'
    fields = ['title', 'textarea']
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.user = Author.objects.get(user=self.request.user)
        fields.save()
        return super().form_valid(form)

notes/templates/notes/add_task.html
{% extends "notes/layout.html" %}
{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'index' %}">Вернуться на гланвую</a>
    <form action="{% url 'add-task' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
    </form>
{% else %}
    <p>Ты должен быть авторизован</p>
{% endif %}
{% endblock %}

notes/templates/notes/all_tasks.html
{% extends 'notes/layout.html' %}

{% block content %}
    <h1>Все задачи</h1>
    <table>
      <thead>
      <tr>
          <td>Title</td>
          <td>Created</td>
          <td>Author</td>
          <td>Status</td>
      </tr>
      </thead>
      <tbody>
      {% if task_list %}
      {% for t in task_list %}
      <tr>
        <td><a href="{% url 'task-detail' t.pk %}">{{ t.title }}</a></td>
        <td>{{ t.created|date }}</td>
        <td>{{ t.user }}</td>
        <td>{{ t.closed|yesno:"Закрыт, Открыт" }}</td>
      </tr>
      {% empty %}
      <tr>
          <td colspan=4>Нет задач.</td>
      </tr>
      {% endfor %}
      </tbody>
      {% endif %}
  </table>

    
 
{% endblock %}

notes/templates/notes/index.html
{% extends 'notes/layout.html' %}

{% block content %}
<h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum voluptate, similique quaerat incidunt nulla 
  beatae id dolore molestias saepe cum consequuntur commodi facilis placeat suscipit soluta repudiandae officiis sint numquam?</h1>

  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum voluptate, similique quaerat incidunt nulla 
    beatae id dolore molestias saepe cum consequuntur commodi facilis placeat suscipit soluta repudiandae officiis sint numquam?</p>

<h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum voluptate, similique quaerat incidunt nulla 
  beatae id dolore molestias saepe cum consequuntur commodi facilis placeat suscipit soluta repudiandae officiis sint numquam?</h2>

  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum voluptate, similique quaerat incidunt nulla 
    beatae id dolore molestias saepe cum consequuntur commodi facilis placeat suscipit soluta repudiandae officiis sint numquam?</p>
  <ul>
    
  </ul>
{% endblock content %}

notes/templates/notes/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'notes/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'notes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'notes/css/all.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <script src="{% static 'notes/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Главная</a></li>
                    <li><a href="{% url 'notes' %}">Все отчеты</a></li>
                    <li><a href="{% url 'users' %}">Все юзеры</a></li>
                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'note-create' %}">Создать отчет</a></li>
                    <li><a href="{% url 'add-task' %}">Добавить задачу</a></li>
                    <li><a href="{% url 'my-tasks' %}">Задачи в работе</a></li>
                    <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                    {% endif %}
                    {% if perms.notes.can_mark_returned %}
                    <li><a href="{% url 'all-tasks' %}">Все задачи в работе</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %} 
            </div>
        </div>
    
    </div>
</body>
</html>

notes/templates/notes/my_task.html
{% extends 'notes/layout.html' %}

{% block content %}
    <h1>Задачи в работе</h1>

    {% if task_list %}
    <ul>
      {% for t in task_list %}
      <li class="{% if t.is_overdue %}text-danger{% endif %}">
        <a href="{{ t.get_absolute_url }}">{{ t.title }}</a> ({{ t.created }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет задач</p>
    {% endif %}
    
{% endblock %}

notes/templates/notes/note_confirm_delete.html
{% extends "notes/layout.html" %}
{% block content %}

<h1>Удалить запись</h1>

<p>Ты уверене, что хочешь удалить эту запись? {{ note }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить." />
</form>

{% endblock %}

notes/templates/notes/note_detail.html
{% extends 'notes/layout.html' %}

{% block content %}
<h1>Title: {{ note.title }}</h1>
<p><strong>Создал: </strong> <a href="">{{ note.user }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Текст: </strong> {{ note.textarea }}</p>
  {% if perms.notes.can_mark_returned %}
    <li><a href="{% url 'note-update' note.id %}">Редактировать</a></li>
    <li><a href="{% url 'note-delete' note.id %}">Удалить</a></li>
  {% endif %}
  <div style="margin-left:20px;margin-top:20px">
    <h4>Кому передано</h4>

    {% for n in note.noteinstance_set.all %}
    <p>Выполняет: {{ n.responsible }}</p>
    <hr>
    <p><strong>Статус: </strong> {% for n in note.noteinstance_set.all %} {{ n }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    <p class="{% if n.status == 'В работе' %}text-success{% elif n.status == 'Отложено' %}text-danger{% else %}text-warning{% endif %}">{{ n.get_status_display }}</p>
    {% if copy.status != 'Отложено' %}<p><strong>Сделать до:</strong> {{n.must_do}}</p>{% endif %}
    <p class="text-muted"><strong>Id:</strong> {{n.id}}</p>
    {% endfor %}
  </div>
{% endblock content %}

notes/templates/notes/note_form.html
{% extends "notes/layout.html" %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

notes/templates/notes/note_list.html
{% extends 'notes/layout.html' %}

{% block content %}
    <h1>Список задач</h1>
      {% if note_list %}
      <ul>

        {% for note in note_list %}
        <li>
          <a href="{{ note.get_absolute_url }}">{{ note.title }}</a> ({{note.user}})
        </li>
        {% endfor %}

      </ul>
      {% else %}
      <p>Нет задач</p>
      {% endif %}
{% endblock %}

notes/templates/notes/renew_note_date_task.html
{% extends "notes/layout.html" %}
{% block content %}

    <h1>Обновление: {{ notetask.note.title }}</h1>
    <p>Передано на: {{ notetask.responsible }}</p>
    <p{% if noteinst.is_created %} class="text-danger" {% endif %}>Должно быть сделано до: {{notetask.must_do}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

notes/templates/notes/task_detail.html
{% extends 'notes/layout.html' %}

{% block content %}
<h1>Title: {{ task.title }} - {{ task.closed|yesno:"ЗАКРЫТО, ОТКРЫТО" }}</h1>
<p><strong>Создал: </strong> <a href="">{{ task.user }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Дата: </strong> {{ task.created }}</p>
<p><strong>Текст: </strong> {{ task.textarea }}</p>
{% endblock %}
  {% comment %} {% if perms.notes.can_mark_returned %}
    <li><a href="{% url 'note-update' task.id %}">Редактировать</a></li>
    <li><a href="{% url 'note-delete' task.id %}">Удалить</a></li>
  {% endif %} {% endcomment %}
  {% comment %} <div style="margin-left:20px;margin-top:20px">
    <h4>Кому передано</h4>

    {% for n in note.task_set.all %}
    <p>Выполняет: {{ n.responsible }}</p>
    <hr>
    <p><strong>Статус: </strong> {% for n in note.task_set.all %} {{ n }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    <p class="{% if n.status == 'В работе' %}text-success{% elif n.status == 'Отложено' %}text-danger{% else %}text-warning{% endif %}">{{ n.get_status_display }}</p>
    {% if n.status != 'Отложено' %}<p><strong>Сделать до:</strong> {{n.must_do}}</p>{% endif %}
    <p class="text-muted"><strong>Id:</strong> {{n.id}}</p>
    <p><strong>Текст: </strong> {{ n.textarea }}</p>
    {% endfor %}
  </div> {% endcomment %}

notes/templates/notes/task_list_borrowed_user.html
{% extends 'notes/layout.html' %}

{% block content %}
    <h1>Задачи в работе</h1>

    {% if task_list %}
    <ul>
      {% for t in task_list %}
      <li class="{% if t.is_overdue %}text-danger{% endif %}">
        <a href="{{ t.get_absolute_url }}">{{ t.title }}</a> ({{ t.must_do }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет задач</p>
    {% endif %}
    
{% endblock %}

notes/templates/notes/user_detail.html
{% extends 'notes/layout.html' %}

{% block content %}
<h1>Пользователь: {{ user.first_name }} {{ user.last_name }}</h1>

  
{% endblock content %}

notes/templates/notes/users.html
{% extends 'notes/layout.html' %}

{% block content %}
    
    {% if users_list %}
    <ul>

    {% for user in users_list %}
    <li>
        <a href="{{ user.get_absolute_url }}">{{ user }}</a> 
    </li>
    {% endfor %}

    </ul>
    {% else %}
    <p>Нет пользователей</p>
    {% endif %} 
{% endblock %}